### ISSUE TITLE
Review too-far-away-from-road-network threshold for facilities

### ISSUE THREAD

**Issue by spalladino** [instedd/planwise#185]
In the current set of Kenyan 4000+ facilities, around half of them are being considered out of the road network. Check some representative examples, and review the current threshold accordingly.

**Comment by nditada** [comment]
We have evidence to believe that most of the errors are likely due to the road network being incomplete and not in the facilities location. Let's adjust the threshold heuristically until we have only 10% of the Kenyan dataset out of the network. In that way, we translate the error to the dataset that is responsible–ie we are decreasing the accuracy of the coverage areas instead of not showing them.

**Comment by mmuller** [comment]
Ok in version 0.5.1-130-gab8d3ae
