### ISSUE TITLE
Reassess using alpha shapes with more points for computing isochrones

### ISSUE THREAD

**Issue by ggiraldez** [instedd/planwise#21]
The current problem with using the alpha shape algorithm for computing isochrones is that it yields a polygon covering much more area than the more accurate method of buffering the reachable roads. This is mainly due to the fact that the alpha shape works on a set of points but has no information of the underlying edges that connect those points. Using those edges, produce more points to feed the alpha shape algorithm and compare the resulting polygons again.

**Comment by fgasperij** [comment]
Instead of using the OSM nodes to feed the pgr_pointsaspolygon function we generated them
by interpolating points at a fixed distance throughout the included ways:
```
select pgr_pointsaspolygon(
  '(select (row_number() over ())::int as id, st_x(point)::float as x, st_y(point)::float as y
    from (select st_lineinterpolatepoint(the_geom,
            meters_between_points/st_length(the_geom::geography)*generate_series(0, floor((1/(meters_between_points/st_length(the_geom::geography))))::int, 1)) as point
        from ways
        where gid in (select gid from edges_agg_cost where agg_cost < to_cost)) as points)')
```
The average distance between consecutive nodes in the same way was 200 mts but there were cases where some nodes
were 1.4 kms apart. We calculated the alpha shapes with 50 mts between points and identified the worst cases by
calculating which were the ones with the most percentage of it's area outside the polygon that generated the buffer algorithm
for the same isochrone: `area(intersection(alpha-shape-polygon, buffer-polygon))/area(alpha-shape-polygon)`. The worst case
corresponded as expected with X like road intersections. The improvement of the unnecessary area calculated by the
alpha shape algorithm with the interpolated points was around 0.02%, not enough to be considered as a buffer alternative.

**Comment by fgasperij** [comment]
We tried to improve the alpha-shape isocrhones by using the points of the buffers of the ways. This was motivated by seeing that what was missing for the alpha shape to improve was some sense of area or shape. The points of the lines of the ways had no area nor shape.
The quality of this alternative was far better. It improved in 89% (0.37 -> 0.70) in comparison with the alpha-shape from the points of the ways. The downside is that the size required was x7 and it took x11 time. The quality was compared by using `area(intersection(buffer_polygon, alpha_shape_polygon))/area(alpha_shape_polygon)`.
