### ISSUE TITLE
Requests can't be canceled

### ISSUE THREAD

**Issue by ftarulla** [instedd/planwise#456]
Using reframe 0.10.5. 

When using the effects `:db` `:api`, the order is important when the effect associated with `:api` changes the DB (although the documentation says the effects run simultaneously)
Effects associated with `:api` **shouldn't modify the DB directly**!

**Comment by ggiraldez** [comment]
See https://github.com/Day8/re-frame-http-fx/pull/18 for a possible solution. Otherwise, a request id could be pre-determined and have the `:api` effect handler keep a reference map in an atom with in-flight requests indexed by such id. Main drawback of this approach is the client code is responsible for ensuring the uniqueness of the ids.
