### ISSUE TITLE
Change suggestions logic

### ISSUE THREAD

**Issue by diegoliberman** [instedd/planwise#553]
In the algorithm that suggests new locations, verify that the impact is measured on the scenario demand, and not on the search raster (which is modified while computing new locations).

**Comment by juanboca** [comment]
This change has an impact on the information presented to the user through the UI. 
Now the suggestions are properly ordered based on the needed capacity (using the suggestion number). And also each one shows the actual needed capacity.

Before:
![Screen Shot 2019-11-12 at 11 16 39](https://user-images.githubusercontent.com/488553/68679908-7effe700-053f-11ea-8937-5ddd0184f28e.png)
Now:
![Screen Shot 2019-11-12 at 11 16 48](https://user-images.githubusercontent.com/488553/68679926-8b843f80-053f-11ea-9846-99192ece793b.png)

Before:
![Screen Shot 2019-11-12 at 11 16 21](https://user-images.githubusercontent.com/488553/68679960-96d76b00-053f-11ea-99a1-28dbcd13cd97.png)
Now:
![Screen Shot 2019-11-12 at 11 16 58](https://user-images.githubusercontent.com/488553/68679986-9f2fa600-053f-11ea-8532-b1fde81d1cc4.png)

Note that all the suggestions are in the same place, since the algorithm to choose them hasn't changed. But the needed capacity is properly calculated

**Comment by mmuller** [comment]
Working properly in version de7e919f
